# Tensorflow - Marker Quality Control

In [1]:
import mlflow
import tensorflow as tf

### Définition sure serveur MLFLOW

In [2]:
model = tf.saved_model.load(
    "marker_quality_control/1", tags=None, options=None
)

In [3]:
img_path = "images/10.jpg"
img = tf.keras.utils.load_img(img_path, target_size=(224, 224))
img_array = tf.keras.utils.img_to_array(img)
img_array = tf.expand_dims(img_array, axis=0)
img_array = img_array / 255.0

In [4]:
img_array

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.3764706 , 0.3372549 , 0.32941177],
         [0.3764706 , 0.3372549 , 0.32941177],
         [0.38431373, 0.34117648, 0.33333334],
         ...,
         [0.74509805, 0.70980394, 0.6745098 ],
         [0.7490196 , 0.7137255 , 0.6784314 ],
         [0.7529412 , 0.7176471 , 0.68235296]],

        [[0.4745098 , 0.44313726, 0.43137255],
         [0.47058824, 0.4392157 , 0.42745098],
         [0.47058824, 0.43137255, 0.42352942],
         ...,
         [0.7529412 , 0.7176471 , 0.68235296],
         [0.7529412 , 0.7176471 , 0.68235296],
         [0.7607843 , 0.7254902 , 0.6901961 ]],

        [[0.5568628 , 0.5372549 , 0.5254902 ],
         [0.5568628 , 0.5372549 , 0.5254902 ],
         [0.5647059 , 0.53333336, 0.52156866],
         ...,
         [0.75686276, 0.72156864, 0.6862745 ],
         [0.7607843 , 0.7254902 , 0.6901961 ],
         [0.7647059 , 0.7294118 , 0.69411767]],

        ...,

        [[0.654902  , 0.654902  , 

In [5]:
model(inputs = img_array)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[2.3617949e-04, 9.9976379e-01]], dtype=float32)>

### Encapsulation dans un mlflow pyfunc modèle


In [6]:
import mlflow

mlflow.set_tracking_uri("http://model-platform.com/registry/test/")
mlflow.pyfunc.log_model(
            artifact_path="custom_model",
            python_model="marker_quality_control_wrapper.py",
            artifacts={"model_path": "marker_quality_control/1"},
            registered_model_name="marker_quality_control"
        )


/Users/philippe.stepniewski/Library/Caches/pypoetry/virtualenvs/model-platform-Rq1uDyp9-py3.11/lib/python3.11/site-packages/mlflow/pyfunc/utils/data_validation.py:186: UserWarning: Add type hints to the `predict` method to enable data validation and automatic signature inference during model logging. Check https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage-in-pythonmodel for more details.
  color_warning(
/Users/philippe.stepniewski/Library/Caches/pypoetry/virtualenvs/model-platform-Rq1uDyp9-py3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025/09/26 19:04:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Successfully registered model 'marker_quality_

In [7]:
model = mlflow.pyfunc.load_model(model_uri="models:/marker_quality_control/1")

/Users/philippe.stepniewski/Library/Caches/pypoetry/virtualenvs/model-platform-Rq1uDyp9-py3.11/lib/python3.11/site-packages/mlflow/pyfunc/utils/data_validation.py:186: UserWarning: Add type hints to the `predict` method to enable data validation and automatic signature inference during model logging. Check https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage-in-pythonmodel for more details.
  color_warning(


In [8]:
model.predict(img)

TypeError: a bytes-like object is required, not 'JpegImageFile'